// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZenBuilds.Helpers;

#nullable disable

namespace ZenBuilds.SqliteMigrations
{
    [DbContext(typeof(SqliteDataContext))]
    partial class SqliteDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("ZenBuilds.Entities.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LikesCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpponentRace")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerRace")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Published")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("ZenBuilds.Entities.Follower", b =>
                {
                    b.Property<int>("User_UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Follower_UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FollowDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("User_UserId", "Follower_UserId");

                    b.HasIndex("Follower_UserId");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("ZenBuilds.Entities.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LikeDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("ZenBuilds.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZenPoints")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ZenBuilds.Entities.UserLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AuthSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("ZenBuilds.Entities.Build", b =>
                {
                    b.HasOne("ZenBuilds.Entities.User", "User")
                        .WithMany("Builds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZenBuilds.Entities.Follower", b =>
                {
                    b.HasOne("ZenBuilds.Entities.User", "Follower_User")
                        .WithMany("Followers")
                        .HasForeignKey("Follower_UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZenBuilds.Entities.User", "User_User")
                        .WithMany("Following")
                        .HasForeignKey("User_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Follower_User");

                    b.Navigation("User_User");
                });

            modelBuilder.Entity("ZenBuilds.Entities.Like", b =>
                {
                    b.HasOne("ZenBuilds.Entities.Build", "Build")
                        .WithMany("BuildLikes")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZenBuilds.Entities.User", "User")
                        .WithMany("LikedBuilds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZenBuilds.Entities.UserLog", b =>
                {
                    b.HasOne("ZenBuilds.Entities.User", "User")
                        .WithMany("UserLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZenBuilds.Entities.Build", b =>
                {
                    b.Navigation("BuildLikes");
                });

            modelBuilder.Entity("ZenBuilds.Entities.User", b =>
                {
                    b.Navigation("Builds");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("LikedBuilds");

                    b.Navigation("UserLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
